### ISSUE TITLE
Ability to specify DNS server for dns_a_record_set data source

### ISSUE THREAD

**Issue by kolesaev** [hashicorp/terraform-provider-dns#394]
### Terraform CLI and Provider Versions

any

### Use Cases or Problem Statement

If we a private network with VMs, then create a DNS server in this network we would be able to use this server to resolve private IP addresses. Currently I use a local-exec with write read to a file.

### Proposal

Add server string argument to put there DNS server IP or IP with port

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxboone** [comment]
Duplicate: https://github.com/hashicorp/terraform-provider-dns/issues/242

**Comment by cunneen** [comment]
If your private DNS server supports a DNS-over-HTTPS JSON API (e.g. [like that provided by Google](https://developers.google.com/speed/public-dns/docs/doh/json), Cloudflare, Alibaba, NextDNS etc), the [module I just published](https://registry.terraform.io/modules/cunneen/http-json/dns/latest) will let you do this. It doesn't support normal `dns-wire-format` messages though, so you're out of luck if your DNS server doesn't provide a JSON API.

Example:

- Use Cloudflare to lookup Apple's NS records

    ```hcl
    module "http-json" {
      source             = "cunneen/http-json/dns"
      name               = "apple.com"
      type               = "NS"
      endpoint           = "https://cloudflare-dns.com/dns-query"
      headers = {
        accept = "application/dns-json"
      }
    }
    ```

    Response:

    ```hcl
    "dns_response" = {
      "AD" = false
      "Answer" = [
        {
          "TTL" = 35116
          "data" = "a.ns.apple.com."
          "name" = "apple.com"
          "type" = 2
        },
        {
          "TTL" = 35116
          "data" = "b.ns.apple.com."
          "name" = "apple.com"
          "type" = 2
        },
        {
          "TTL" = 35116
          "data" = "c.ns.apple.com."
          "name" = "apple.com"
          "type" = 2
        },
        {
          "TTL" = 35116
          "data" = "d.ns.apple.com."
          "name" = "apple.com"
          "type" = 2
        },
      ]
      "CD" = false
      "Question" = [
        {
          "name" = "apple.com"
          "type" = 2
        },
      ]
      "RA" = true
      "RD" = true
      "Status" = 0
      "TC" = false
    }
    ```

**Comment by kolesaev** [comment]
@cunneen , thanks for sharing

Unfortunately it doesn't solve the issue if i need to resolve a hostname from a private hosted zone, which is accessible only on the hosts connected this private hosted zone

In other hand, we are able to create an API project with any programming language to resolve IPs and use it via **_hashicorp/http_** provider. But will look forward it's implemented in **_hashicorp/dns_** provider
